version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - docker_academic-net

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - docker_academic-net

  searchapp:
    build: 
      context: ../
      dockerfile: Docker/Dockerfile
    container_name: academic-search-app
    ports:
      - "8501:8501"
    depends_on:
      - elasticsearch
      - minio
    volumes:
      - ./model_cache:/root/.cache/huggingface
    env_file:
      - .env
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.runOnSave=true
    networks:
      - docker_academic-net

  academic-search-monitor:
    build: 
      context: ../
      dockerfile: Docker/Dockerfile
    container_name: academic-search-monitor
    ports:
      - "8502:8502"
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SECURE=false
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - STREAMLIT_SERVER_PORT=8502
    volumes:
      - ./model_cache:/root/.cache/huggingface
    depends_on:
      - elasticsearch
      - minio
    command: streamlit run monitor/dashboard.py
    networks:
      - docker_academic-net
    restart: unless-stopped

volumes:
  minio-data:

networks:
  docker_academic-net:
    driver: bridge
